apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: hackapp
  namespace: default
spec:
  destinationSelectors:
  - matchLabels:
      environment: dev
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: hackapps.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: hackapp
        plural: hackapps
        singular: hackapp
      scope: Namespaced
      versions:
      - name: v1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  teamName:
                    type: string
                    description: Your team name for the hackathon, this will be used as your namespace in k8s
                  dbDriver:
                    default: none
                    description: database deployed with application
                    enum:
                    - postgresql
                    - mongodb
                    - none
                    type: string
                  image:
                    description: container image for application that will be deployed
                    example: gcr.io/syntasso/great-app
                    type: string
                    properties:
                    env:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                        required:
                        - name
                        - value
                  name:
                    type: string
                  service:
                    type: object
                    properties:
                      port:
                        type: integer

                required:
                - teamName
                - name
                - image
                type: object
            type: object
        served: true
        storage: true
  requiredPromises:
    - name: postgresql
      version: v1.0.0-beta.1
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: resource-configure
          spec:
            containers:
              - name: create-resources
                image: ghcr.io/phiph/hackathon-as-a-service/hack-as-a-service:latest
                command: [ resource-configure ]
              - name: database-configure
                image: ghcr.io/phiph/hackathon-as-a-service/hack-as-a-service:latest
                command: [ database-configure ]
status: {}
